source 'https://rubygems.org'
# created by inline_forms 5.1.1 on {Date.today}
ruby "2.4.1"

gem 'cancancan', '~> 2.0'
gem 'carrierwave'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'coffee-rails'
gem 'devise'
gem 'bootstrap', '~> 4.1.3'
gem 'octicons_helper'
gem 'i18n-active_record', git: 'https://github.com/acesuares/i18n-active_record.git'
gem 'inline_forms', git: 'https://github.com/ortegacmanuel/inline_forms.git', branch: 'bootstrap'
gem 'jquery-rails'
gem 'jquery-timepicker-rails'
gem 'jquery-ui-sass-rails'
gem 'mini_magick'
gem 'mysql2'
gem 'paper_trail'
gem 'rails-i18n'
gem 'rails', '~> 5.1.4'
gem 'rake'
gem 'remotipart', '~> 1.0'
gem 'rvm'
gem 'sass-rails'
gem 'tabs_on_rails'
gem 'therubyracer'
gem 'uglifier'
gem 'figaro'
gem 'unicorn'
gem 'validation_hints'
gem 'will_paginate'
gem 'turbolinks', '~> 5'
gem 'autoprefixer-rails', '~> 8.3'
gem 'bootstrap-datepicker-rails'
gem 'pg'
group :development do
  gem 'bundler'
  gem 'listen'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'seed_dump', git: 'https://github.com/acesuares/seed_dump.git'
  gem 'shoulda'
  gem 'sqlite3'
  gem 'switch_user'
  gem 'yaml_db'
  gem 'capistrano', '~> 3.6', require: false
  gem 'capistrano-rails', '~> 1.3', require: false
  gem 'capistrano-bundler', '~> 1.3', require: false
  gem 'rvm1-capistrano3', require: false
  gem 'capistrano3-unicorn'
  gem 'byebug'
  gem 'rails-erd'
end
